import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars = {
    tutorialSidebar: [
        'intro',
        'installation',
        'modules-overview',
        'supported-versions',
        'why-qabase',
        'release-notes',

        // Module categories first
        {
            type: 'category',
            label: 'Core',
            link: { type: 'doc', id: 'core/index' },
            items: [{ type: 'autogenerated', dirName: 'core' }],
        },
        {
            type: 'category',
            label: 'REST',
            link: { type: 'doc', id: 'rest/index' },
            items: [{ type: 'autogenerated', dirName: 'rest' }],
        },
        {
            type: 'category',
            label: 'WebUI',
            link: { type: 'doc', id: 'webui/index' },
            items: [{ type: 'autogenerated', dirName: 'webui' }],
        },

    ],
};

export default sidebars;
